### ISSUE TITLE
Make the website fully responsive

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#13]
I still see a horizontal scroll-bar when I resize the window. Does anyone know off the top of their head, how to get rid of it?

**Comment by emilsoman** [comment]
The website currently supports 3 media resolutions (desktop, tablet(portrait) and mobile(portrait) ). This came in with the theme that we're using right now. You see the scrollbar when the resolution doesn't fall in those 3 categories. Looks like [it works works fine in portrait mode on majority of devices](http://www.responsinator.com/?url=www.gardencityruby.org).  

@kgrz  is there an easy way to make it fully responsive without changing the design too much ?

**Comment by kgrz** [comment]
The responsive breakpoints need to be fine tuned. I'll get this done.

**Comment by kgrz** [comment]
Fixed by https://github.com/GardenCityRuby/GCRC2014/commit/05358e8f8ed5f9248cf1fba0b20730767109318c

**Comment by swanandp** [comment]
Done. :+1:
