### ISSUE TITLE
What features can we leave out?

### ISSUE THREAD

**Issue by kgrz** [GardenCityRuby/GCRC2014#2]
##### 1. Do we need Disqus-related material?

The blog articles part has a lot of styles and placeholders for Disqus comments. Would we need comments on the blog part of the website? Or just a twitter link / email form for queries suffice?

---
##### 2. As of now, the top level navigation bar has 7 links.

I'm planning to drop the following hyperlinks while in a smaller viewport:
1. About
2. Tickets (This will be in the body of the front page and not in the nav)
3. Twitter ( instead of a link, a twitter image will be used)
4. Schedule ( This too, will be in the body of the front page)

Or else, if we need all the links, we would have to use a select bar similar to the one used here: [http://recipes.sinatrarb.com/](http://recipes.sinatrarb.com/)

Views?

/ cc @emilsoman

**Comment by swanandp** [comment]
I think we should keep Disqus. Commenting is good for PR.

**Comment by emilsoman** [comment]
We will need a footer and put the social network links there. We'll also include a link on the footer for ' code of conduct ' . I am thinking we can move the ' about ' link to the footer as well.

I also think venue , date and tickets can be on the homepage. Wouldn't it be too cluttered if we keep the schedule on the homepage ? We don't want users to get lost on the homepage and miss important information because there's too much stuff .

Disqus is needed . Are the styles going to conflict with new ones ?

**Comment by kgrz** [comment]
@emilsoman Agree. Detailed schedule will get a separate page. May be, one way would be to host the schedule on lanyrd and then just have a link pointing there.

@swanandp Okay. Disqus stays…until further counter-argument.

Will we be needing a twitter feed in the footer? Or just a logo with the link pointing to twitter.com/gardencityrb? And do we have a presence on other networks as well? If yes, I need those links.

Some of the things/clarifications I need to make further changes:
- [ ] Logo's source. Or the freedom to do another copy without modifying the existing design.
- [ ] Links to social networks.
- [ ] I'm assuming the CFP is still going on? We probably have to have some information about the dates.
- [ ] Do we need to cater to IE < 9-10?
- [ ] Sponsor prospectus?

**Comment by prakashmurthy** [comment]
@emilsoman YOU OWN THE WEBSITE COMPONENT. COULD YOU PLEASE FOLLOW THROUGH ON WHAT WE DISCUSSED EARLIER TODAY AND HAVE THE WEBSITE UPDATED ASAP?

ALL CHANGES RELATED TO THE WEBSITE CAN HAPPEN INCREMENTALLY AFTER WE HAVE THE ORIGINAL SET OF FEATURES DEPLOYED.

**Comment by emilsoman** [comment]
@kgrz 
- [x] Logo's source - https://github.com/GardenCityRuby/GCRC-logo
- [x] Links to social networks - Only twitter right now. Lanyrd [link](http://lanyrd.com/2014/garden-city-ruby-conference/) 
- [x] CFP - This will be done using BusyConf. We'll just add [the link to the BusyConf page](https://gardencityruby2014.busyconf.com/proposals/new)
- [x] Do we need to cater to IE < 9-10? - No 
- [x] Sponsor prospectus? - I've added the PDF link, Satish is working on the HTML version for the website.

Please close this issue if you got what you wanted.

**Comment by swanandp** [comment]
Are we done with this, or is anything pending?

**Comment by kgrz** [comment]
Can be closed.

On Wednesday, October 23, 2013, Swanand Pagnis wrote:

> Are we done with this, or is anything pending?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/2#issuecomment-26884764
> .

## 

Kashyap KMBC

**Comment by swanandp** [comment]
Ok, thanks @kgrz !
