### ISSUE TITLE
Google Search Result Summary is weird

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#22]
Have a look at the summary of GCRC website when googled for "garden city ruby". 
![screen shot 2013-10-22 at 12 46 08 pm](https://f.cloud.github.com/assets/90904/1379292/78190208-3aea-11e3-910e-3e2840b61d7e.png)

**Comment by emilsoman** [comment]
Wow ! Looking into this right away

**Comment by emilsoman** [comment]
Just noticed the description on lanyrd page says dates are 4,5 Jan instead of 3,4 Jan. @prakashmurthy , will you be able to change that ?

**Comment by swanandp** [comment]
:+1:
