### ISSUE TITLE
Low priority: Titles of all pages point to the ugly /title/index.html link

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#23]
e.g. Go to http://www.gardencityruby.org/sponsors/ and mouse over to the title: 

![screen shot 2013-10-23 at 12 44 58 pm](https://f.cloud.github.com/assets/90904/1388084/0aab238a-3bb3-11e3-84a5-ac55499caa78.png)

**Comment by kgrz** [comment]
Looks like this can be closed.

**Comment by emilsoman** [comment]
@kgrz , why close ? The issue's still there, isn't it ?

**Comment by kgrz** [comment]
Ah! Yes. My bad. I thought the issue was about the sidebar titles. This
still needs a fix.

On Tue, Nov 12, 2013 at 3:34 PM, Emil Soman notifications@github.comwrote:

> @kgrz https://github.com/kgrz , why close ? The issue's still there,
> isn't it ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/23#issuecomment-28281302
> .

## 

Kashyap KMBC
