### ISSUE TITLE
Share blogpost via twitter doesn't include link

### ISSUE THREAD

**Issue by prakashmurthy** [GardenCityRuby/GCRC2014#25]
Only the following text comes up "72 talk proposals in total via @gardencityrb"

See https://twitter.com/gautamrege/status/394776684919922689

**Comment by prakashmurthy** [comment]
@emilsoman This is likely because I saved the html source from the original markdown file (for adding the html/js code for the graphs) from the local dev environment. Will fix this.

**Comment by emilsoman** [comment]
Yeah, that seemed to be the issue. The links are working fine on other pages. That blog post is kickass. The charts look nice !

**Comment by kgrz** [comment]
https://github.com/GardenCityRuby/GCRC2014/commit/410f70fc82ec59905f422f4ed6799e0f1bd2a29d Fixed 

/ cc @prakashmurthy
