### ISSUE TITLE
Blog index page does not show summary for the "72 Talk Proposals in Total" post

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#26]
http://www.gardencityruby.org/blog/ 

No summary text shows up below "72 Talk Proposals in Total"

![screen shot 2013-10-28 at 4 58 09 pm](https://f.cloud.github.com/assets/90904/1419113/1fedc72e-3fc4-11e3-8189-2766cea1d33d.png)

**Comment by emilsoman** [comment]
Looks like this is related to #25 . @prakashmurthy , please let me know if this bug still exists after you push the fix for #25  .

**Comment by kgrz** [comment]
https://github.com/GardenCityRuby/GCRC2014/commit/410f70fc82ec59905f422f4ed6799e0f1bd2a29d Fixes this.

**Comment by swanandp** [comment]
Same issue again.

**Comment by swanandp** [comment]
@kgrz Anything you can do here?

**Comment by kgrz** [comment]
Ah. Yes. An excerpt YAML front matter can be added to force the display of
the excerpt. I'll find a nicer way and see if I can avoid the repetition
(The previous commit that I sent refactoring this was reverted as it
altered part of the matter on the view).

On Mon, Nov 11, 2013 at 4:19 PM, Swanand Pagnis notifications@github.comwrote:

> @kgrz https://github.com/kgrz Anything you can do here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/26#issuecomment-28189471
> .

## 

Kashyap KMBC

**Comment by swanandp** [comment]
Correct, we want the content to not change.
