### ISSUE TITLE
Include program (schedule) in website

### ISSUE THREAD

**Issue by prakashmurthy** [GardenCityRuby/GCRC2014#36]
Need a link to http://gardencityruby2014.busyconf.com/schedule/full with some text. 

The CFP link & page can be removed; no use having it anymore.

**Comment by swanandp** [comment]
@leenasn Any chance we can wrap this up? The iframe idea was good. We should also provide a direct link to BusyConf in order to make it easily searchable.

**Comment by leenasn** [comment]
@swanandp I can take care of integrating iframe, but would need some help with cross browser testing and fixing issues especially with iPad. Can Kashyap or someone help me for testing once I push the PR?

**Comment by swanandp** [comment]
@kgrz - how about this?

**Comment by swanandp** [comment]
Short link to use: [`http://bit.ly/gcrc-schedule`](http://bit.ly/gcrc-schedule)

**Comment by swanandp** [comment]
What we have is good enough.
