### ISSUE TITLE
Page variables not being interpreted

### ISSUE THREAD

**Issue by char-star** [GardenCityRuby/GCRC2014#38]
On the blog listing page, the page variables are not being interpreted by the liquid template parser.
Problem only occurs in the production server, It works fine in my system.

I reckon problem with jekyll version. What is the version in production?
It works fine in 1.2.1

**Comment by gnufied** [comment]
Ah, okay then we should update `Gemfile` to have `jeklly 1.2.1`. Production servers don't have any inherent jekyll version dependency.

`Gemfile.lock` currently points to `1.0.3` version!

**Comment by kgrz** [comment]
But I tested it on the latest jekyll and saw the same issue? Will check and
confirm tonight.

On Monday, November 11, 2013, Hemant Kumar wrote:

> Ah, okay then we should update Gemfile to have jeklly 1.2.1. Production
> servers don't have any inherent jekyll version dependency.
> 
> Gemfile.lock currently points to 1.0.3 version!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/38#issuecomment-28182053
> .

## 

Kashyap KMBC

**Comment by kgrz** [comment]
I was wrong. The update to 1.2.1 does fix this issue. Pushed the update: https://github.com/GardenCityRuby/GCRC2014/pull/43
