### ISSUE TITLE
Remove .html from titles

### ISSUE THREAD

**Issue by ghost** [GardenCityRuby/GCRC2014#4]
You can do that either by URL rewrites, or by replacing postname.html with postname/index.html 

Examples: 
http://www.gardencityruby.org/sponsors.html
http://www.gardencityruby.org/blog.html

**Comment by emilsoman** [comment]
@codepodu , are you talking abour replacing "http://gardencityruby.org/sponsors.html" with "http://gardencityruby.org/sponsors" ?

**Comment by ghost** [comment]
Yes, @emilsoman . Cleaner URLs
