### ISSUE TITLE
Add GoodWorkLabs logo

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#40]
Logo added to shared Dropbox folder.

**Comment by char-star** [comment]
I have added it. Will send a PR

**Comment by char-star** [comment]
I am going to remove the 'Become One' link in the sponsors sections. It isn't really fitting in the design. What do you think? @swanandp @emilsoman @kgrz
And also the empty section for Gold isn't looking good. Will remove that too?

**Comment by swanandp** [comment]
I think "Become One" can be a button.

**Comment by kgrz** [comment]
Yep, agree with Swanand. I kept the link as a temporary placeholder. Will
throw in a button later tonight.

On Monday, November 11, 2013, Swanand Pagnis wrote:

> I think "Become One" can be a button.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/40#issuecomment-28187418
> .

## 

Kashyap KMBC

**Comment by char-star** [comment]
Ok I'll leave it as it is for now.

**Comment by swanandp** [comment]
This issue is fixed.
