### ISSUE TITLE
Sponsors dedicated page

### ISSUE THREAD

**Issue by char-star** [GardenCityRuby/GCRC2014#41]
We need a separate page for sponsors with their logo and blurb. The bottom section in the existing sponsors page can also be used. @kgrz

**Comment by kgrz** [comment]
I'm thinking to remove the "associate", "gold" etc. differentiation from the home page and just list all the sponsors. The separate "sponsors" page will have the differentiation. Any thoughts on this?

**Comment by swanandp** [comment]
Nope, that is unfair to the Gold and Silver sponsors. We're better off
mentioning them explicitly.

**Comment by char-star** [comment]
I go with Swanand. Lets leave it as it is now.

**Comment by kgrz** [comment]
Okay.​

**Comment by emilsoman** [comment]
I too think the bottom part of the [existing sponsors page](http://www.gardencityruby.org/sponsors/) can be used instead of creating a new page for this.

**Comment by swanandp** [comment]
We can safely close this now.
