### ISSUE TITLE
Dedicated Schedule Page with our own design

### ISSUE THREAD

**Issue by swanandp** [GardenCityRuby/GCRC2014#55]
We need to have a great looking schedule page and not depend on Busyconf for the schedule.

**Comment by leenasn** [comment]
@swanandp Not sure whether its better to use iframes so that we can reuse the content from BusyConf. AFAIK, their schedule page is responsive.

**Comment by swanandp** [comment]
@leenasn I'd use the iframe temporarily, but I think it is better to have our own design.

**Comment by prakashmurthy** [comment]
For RubyConf India 2014's usage of busyconf, the arrangement is to have an exclusive mobile app sponsor and split the sponsorship amount between Busyconf & RubyConf India team; the sponsor will get an ad link on the schedule page for attendees to see forever. The schedule functionality provided by busyconf is something they consider worth having people pay for it. 

Am mentioning this to highlight the value of the busyconf schedule functionality in the decision to go for own design or use their version.

**Comment by swanandp** [comment]
Hmm.. it is not behaving responsive for me. Do we need to log a bug in BusyConf ?

![screen shot 2013-11-13 at 9 10 39 pm](https://f.cloud.github.com/assets/90904/1532649/254b17f4-4c7a-11e3-8fe3-98889930d31c.png)

**Comment by prakashmurthy** [comment]
Looks good on most mobile devices: http://www.responsinator.com/?url=http://gardencityruby2014.busyconf.com/schedule#day_5265f6dfd98b6a0018000022 

On desktop, it doesn't seem to be responsive to screen size changes. Worth checking with Ryan (via email) if he can do anything about this.

**Comment by swanandp** [comment]
Alright, created a short link for easy sharing: http://bit.ly/gcrc-schedule

**Comment by swanandp** [comment]
Closing this in favor of using busyconf schedule.
