### ISSUE TITLE
Remove twitter link; include an icon, and position it appropriately.

### ISSUE THREAD

**Issue by prakashmurthy** [GardenCityRuby/GCRC2014#7]
Also include an icon for lanyrd with appropriate link. May require a facebook icon as well later on after a Facebook page is set. 

In addition provide a email icon, with link to mailto:team@gardencityruby.org

**Comment by emilsoman** [comment]
@kgrz , aren't you already working on this, please confirm

**Comment by prakashmurthy** [comment]
I put the [twitter link back in the menu](https://github.com/GardenCityRuby/GCRC2014/commit/3b43c958575f7e0e0d139b44757d7c1c1272bc61) ; let it be there till its replaced with an icon else where.

**Comment by prakashmurthy** [comment]
What happened to this issue?

**Comment by kgrz** [comment]
https://github.com/GardenCityRuby/GCRC2014/commit/08469f2f2375d8981f94f02ba23451aad309a6e7

**Comment by prakashmurthy** [comment]
Forgot this part: 

Also include an icon for lanyrd with appropriate link. 

In addition provide a email icon, with link to mailto:team@gardencityruby.org

**Comment by emilsoman** [comment]
@kgrz , I think it would be best to have a horizontal bar with 3 square icons for twitter, lanyrd and email . You can see how the social share icons look like on the blog posts as a reference.

**Comment by kgrz** [comment]
I thought of having all the three side-by-side where the twitter icon is
now.

On Monday, October 7, 2013, Emil Soman wrote:

> @kgrz https://github.com/kgrz , I think it would be best to have a
> horizontal bar with 3 square icons for twitter, lanyrd and email . You can
> see how the social share icons look like on the blog posts as a reference.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/7#issuecomment-25793811
> .

## 

Kashyap KMBC

**Comment by emilsoman** [comment]
@kgrz , that should be good. Please go ahead with that

**Comment by prakashmurthy** [comment]
Can this issue be resolved to satisfactory completion soon please?

**Comment by emilsoman** [comment]
@kgrz , please update. Once you push the change, we can also add a github icon to the social icons group so folks can fork the site as well.

**Comment by kgrz** [comment]
Right. I had this done a while ago but added text links. I'm yet to find a neat icon package that has a square email icon as the lanyrd one I obtained is a square one and the whole thing looks out of place :/ 

Can a text link to email suffice? Rest (lanyrd, github) will be icons.

**Comment by prakashmurthy** [comment]
Thanks. Skip the email for now.

**Comment by kgrz** [comment]
Okay. After a _long_ delay, https://github.com/GardenCityRuby/GCRC2014/commit/97d10d77f8916630486b10655183433ad23b0d5b should fix this.

**Comment by kgrz** [comment]
Forgot to mention. I added a GitHub logo as well. So, either the logo can be removed or the ribbon. Pick one :) 

Because,

![screenshot](https://f.cloud.github.com/assets/400299/1415093/b02eb89c-3eda-11e3-9962-3cec4bcfb208.png)

and

http://www.responsinator.com/?url=www.gardencityruby.org

**Comment by prakashmurthy** [comment]
Cool; thanks for the responsinator link; fascinating to see how the website looks on different devices. 

I think it is ok having the ribbon over-lap some of the text in the header. 

Am closing this issue. If possible, please move twitter logo in line with the other icons - so all icons are in one line at the bottom.

**Comment by kgrz** [comment]
Okay.
