### ISSUE TITLE
Make the about page look cool

### ISSUE THREAD

**Issue by prakashmurthy** [GardenCityRuby/GCRC2014#8]
http://www.gardencityruby.org/about/ has the minimum information required on the page. Go crazy with making it look cooler. ;-) 

One possible improvement could be to link gravatar images for the team member links.  See the bottom of http://nickelcityruby.com for an example.

**Comment by swanandp** [comment]
@kgrz - Can you get your creative juices flowing on this one? We gotta earn some swag!

**Comment by swanandp** [comment]
Closing this, with sadness.

**Comment by kgrz** [comment]
:|
