### ISSUE TITLE
Add promotional badges to the website

### ISSUE THREAD

**Issue by char-star** [GardenCityRuby/GCRC2014#81]
We need the following three in two size variations - 120px and 220px width
1. I am speaking at Garden City RubyConf 2014
2. I am attending Garden City RubyConf 2014
3. I am sponsoring Garden City RubyConf 2014

Sample design created by @kgrz
![speaking](https://f.cloud.github.com/assets/1221901/1641472/dba53cfa-5855-11e3-9ab4-568fc6d20b39.png)

Refer: http://rubyconfindia.org/2013/badges.html

**Comment by char-star** [comment]
@kgrz can you send me the psd of the design? /cc @emilsoman

**Comment by kgrz** [comment]
Yeah. Will send the finished set. However, is there a vector source for the
logo mark of GCRC?

On Monday, December 2, 2013, Satish Kumar Perala wrote:

> @kgrz https://github.com/kgrz can you send me the psd of the design?
> /cc @emilsoman https://github.com/emilsoman
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/GardenCityRuby/GCRC2014/issues/81#issuecomment-29634234
> .

## 

Kashyap KMBC

**Comment by emilsoman** [comment]
You can find the logos in the gardencityruby github org .

**Comment by kgrz** [comment]
@emilsoman The jekyll branch?

**Comment by char-star** [comment]
@kgrz It's here https://github.com/GardenCityRuby/GCRC-logo

**Comment by kgrz** [comment]
Oh! that. Thanks

**Comment by char-star** [comment]
@kgrz any update on this?

**Comment by kgrz** [comment]
@char-star https://github.com/kgrz/GCRC2014/commit/3149edfd8766b3b736e1173cca569e942936b608

**Comment by char-star** [comment]
Thanks @kgrz ... Added a page https://github.com/GardenCityRuby/GCRC2014/pull/89
