### ISSUE TITLE
Remove duplication of config

### ISSUE THREAD

**Issue by prakashmurthy** [GardenCityRuby/GCRC2014#9]
Adding/removing links would require making changes in 3 files as of now:
- _config.yml
- _config_deploy.yml
- _config_github_pages.yml

Figure out a erb-esque way to have only one place to make the changes.

**Comment by ghost** [comment]
Yep, got bitten by this bug in the morning. YAML supports inheritance, i'll see how i can use it here.

**Comment by emilsoman** [comment]
Had a chat with @gnufied , we thought we'll just gitignore `_config.yml` and keep an example config. I'll add a step in `README` and that should do it.

**Comment by emilsoman** [comment]
@codepodu Would be cool if we could reuse a config template and just override the "url" for github pages and prod !
